Repository maelchiotti/LocalMaterialNotes, pull requests merged in 2024-05, with the labels that each got.

#47 Deactivate appbar buttons
  lib/common/navigation/app_bars/editor_app_bar.dart
  lib/pages/editor/editor_page.dart
  lib/utils/constants/constants.dart
Labels: enhancement

#48 [43] Remove "Untitled note" label
  lib/common/widgets/note_tile.dart
  lib/l10n/app_en.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_localizations.g.dart
  lib/l10n/app_localizations_en.g.dart
  lib/l10n/app_localizations_fr.g.dart
  lib/l10n/app_localizations_tr.g.dart
  lib/l10n/app_tr.arb
  lib/models/note/note.dart
Labels: enhancement

#51 [50] Fix providers and confirmations
  lib/common/actions/delete.dart
  lib/common/actions/pin.dart
  lib/common/actions/restore.dart
  lib/common/dialogs/confirmation_dialog.dart
  lib/common/fabs/fab_empty_bin.dart
  lib/common/navigation/app_bars/selection_app_bar.dart
  lib/pages/editor/editor_page.dart
  lib/providers/bin/bin_provider.dart
  lib/providers/notes/notes_provider.dart
Labels: bug

#53 [52] Improve toolbar
  lib/pages/editor/editor_page.dart
  lib/providers/notes/notes_provider.dart
  lib/utils/constants/paddings.dart
Labels: bug, enhancement

#55 [54] Go back from settings
  lib/common/navigation/side_navigation.dart
Labels: enhancement

#61 [56] [59] Improve markdown export
  README.md
  android/app/build.gradle
  lib/common/widgets/note_tile.dart
  lib/models/note/note.dart
  lib/pages/editor/about_sheet.dart
  lib/pages/editor/editor_page.dart
  lib/pages/editor/editor_toolbar.dart
  lib/pages/settings/settings_actions.dart
  lib/pages/settings/settings_page.dart
  lib/utils/constants/constants.dart
  lib/utils/constants/sizes.dart
  lib/utils/database_manager.dart
  lib/utils/theme_manager.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#65 [62] Sort notes after editing them
  lib/common/fabs/fab_empty_bin.dart
  lib/models/note/note.dart
  lib/providers/bin/bin_provider.dart
  lib/providers/notes/notes_provider.dart
  lib/utils/database_manager.dart
Labels: bug

#67 Prepare v1.3.0
  .github/workflows/build.yaml
  CHANGELOG.md
  README.md
  android/settings.gradle
  assets/data/data_screenshots.json
  docs/screenshots/bin.jpg
  docs/screenshots/bin_selection.jpg
  docs/screenshots/black_dynamic_theming.jpg
  docs/screenshots/editor_about.jpg
  docs/screenshots/editor_advanced.jpg
  docs/screenshots/editor_simple.jpg
  docs/screenshots/grid_view.jpg
  docs/screenshots/latest_bin.jpg
  docs/screenshots/latest_editor.jpg
  docs/screenshots/latest_notes.jpg
  docs/screenshots/latest_notes_selection.jpg
  docs/screenshots/latest_search.jpg
  docs/screenshots/latest_settings_1.jpg
  docs/screenshots/latest_theme_dynamic_dark.jpg
  docs/screenshots/latest_theme_dynamic_light.jpg
  docs/screenshots/light_dynamic_theming.jpg
  docs/screenshots/light_theming.jpg
  docs/screenshots/notes.jpg
  docs/screenshots/notes_selection.jpg
  docs/screenshots/search.jpg
  docs/screenshots/settings.jpg
  docs/screenshots/settings_2.jpg
  docs/screenshots/sort.jpg
  docs/screenshots/v1.1.2_editor_about.jpg
  docs/screenshots/v1.1.2_selection_bin.jpg
  docs/screenshots/v1.1.2_settings_2.jpg
  docs/screenshots/v1.1.2_sort.jpg
  docs/screenshots/v1.1.2_theme_dynamic_black.jpg
  docs/screenshots/v1.1.2_theme_light.jpg
  lib/app.dart
  lib/common/navigation/app_bars/notes_app_bar.dart
  lib/l10n/hardcoded_localizations.dart
  lib/main.dart
  lib/pages/settings/settings_actions.dart
  lib/pages/settings/settings_page.dart
  lib/providers/base_provider.dart
  lib/providers/bin/bin_provider.dart
  lib/providers/notes/notes_provider.dart
  lib/utils/constants/constants.dart
  lib/utils/database_utils.dart
  lib/utils/info_utils.dart
  lib/utils/locale_utils.dart
  lib/utils/preferences/confirmations.dart
  lib/utils/preferences/layout.dart
  lib/utils/preferences/preference_key.dart
  lib/utils/preferences/preferences_utils.dart
  lib/utils/preferences/sort_method.dart
  lib/utils/quick_actions_utils.dart
  lib/utils/share_utils.dart
  lib/utils/snack_bar_utils.dart
  lib/utils/theme_utils.dart
  pubspec.lock
  pubspec.yaml
Labels: documentation

#73 add spanish translations
  README.md
  lib/l10n/app_es.arb
  lib/l10n/app_localizations.g.dart
  lib/l10n/app_localizations_en.g.dart
  lib/l10n/app_localizations_es.g.dart
  lib/l10n/app_localizations_fr.g.dart
  lib/l10n/app_localizations_tr.g.dart
  lib/l10n/hardcoded_localizations.dart
Labels: localization

#79 Splash screen for Android 12
  android/app/build.gradle
  android/app/src/main/res/drawable-hdpi/android12splash.png
  android/app/src/main/res/drawable-mdpi/android12splash.png
  android/app/src/main/res/drawable-night-hdpi/android12splash.png
  android/app/src/main/res/drawable-night-mdpi/android12splash.png
  android/app/src/main/res/drawable-night-xhdpi/android12splash.png
  android/app/src/main/res/drawable-night-xxhdpi/android12splash.png
  android/app/src/main/res/drawable-night-xxxhdpi/android12splash.png
  android/app/src/main/res/drawable-xhdpi/android12splash.png
  android/app/src/main/res/drawable-xxhdpi/android12splash.png
  android/app/src/main/res/drawable-xxxhdpi/android12splash.png
  android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  assets/icons/icon.ico
  assets/icons/icon_android_12.png
  flutter_native_splash.yaml
  lib/common/navigation/side_navigation.dart
  lib/l10n/app_localizations.g.dart
  lib/l10n/app_localizations_en.g.dart
  lib/l10n/app_localizations_es.g.dart
  lib/l10n/app_localizations_fr.g.dart
  lib/l10n/app_localizations_tr.g.dart
  lib/pages/settings/settings_actions.dart
  lib/utils/asset.dart
  lib/utils/extensions/validators/string_validators.dart
  pubspec.yaml
Labels: bug

#80 [74] Fix going back from licenses list
  lib/pages/settings/settings_actions.dart
Labels: bug
